#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/03ae2bc1-c257-4760-bbbf-9d067a37e7e2/ # 

version: v1.0
title: Salesforce Account API

securitySchemes:
  oauth_2_0:
    description: |
      This API supports OAuth 2.0 for authenticating all API requests.
    type: OAuth 2.0
    describedBy:
      queryParameters:
        access_token:
          description: |
             Used to send a valid OAuth 2 access token.
          type: string
      responses:
        400:
          description: Invalid token.
        401:
          description: |
            Unauthorized or Connection error when connecting to the authorization server.
        403:
          description: |
            Forbidden, invalid client application credentials.
        500:
          description: |
            Bad response from authorization server, or WSDL SOAP Fault error.
    settings:
      authorizationUri: https://dev-536244.okta.com/oauth2/default/v1/authorize
      accessTokenUri: https://dev-536244.okta.com/oauth2/default/v1/token
      authorizationGrants: [client_credentials]
      
        

/accounts:
  get:
    securedBy: [oauth_2_0]
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "accounts": [
                  {
                    "accountId": "0014I00001qsS4lQAE",
                    "tradingName": "GenePoint",
                    "accountNumber": "CC978213",
                    "industry": "Biotechnology",
                    "contacts": [
                      {
                        "firstName": "Edna",
                        "lastName": "Frank",
                        "title": "VP, Technology",
                        "email": "efrank@genepoint.com",
                        "phone": "(650) 867-3450"
                      },
                      {
                        "firstName": "Edna",
                        "lastName": "Frank",
                        "title": "VP, Technology",
                        "email": "efrank@genepoint.com",
                        "phone": "(650) 867-3450"
                      }
                    ],
                    "links": [
                      {
                        "rel": "self",
                        "href": "accounts/0014I00001qsS4lQAE"
                      }
                    ]
                  },
                  {
                    "accountId": "0014I00001qsS4lQAE",
                    "tradingName": "GenePoint",
                    "accountNumber": "CC978213",
                    "industry": "Biotechnology",
                    "contacts": [
                      {
                        "firstName": "Edna",
                        "lastName": "Frank",
                        "title": "VP, Technology",
                        "email": "efrank@genepoint.com",
                        "phone": "(650) 867-3450"
                      },
                      {
                        "firstName": "Edna",
                        "lastName": "Frank",
                        "title": "VP, Technology",
                        "email": "efrank@genepoint.com",
                        "phone": "(650) 867-3450"
                      }
                    ],
                    "links": [
                      {
                        "rel": "self",
                        "href": "accounts/0014I00001qsS4lQAE"
                      }
                    ]
                  }
                ]
              }
  /{accountId}:
    get:
      responses:
        200:
          body:
            application/json:
              example: | 
                {
                  "accountId": "0014I00001qsS4lQAE",
                  "tradingName": "GenePoint",
                  "accountNumber": "CC978213",
                  "industry": "Biotechnology",
                  "contacts": [
                    {
                      "firstName": "Edna",
                      "lastName": "Frank",
                      "title": "VP, Technology",
                      "email": "efrank@genepoint.com",
                      "phone": "(650) 867-3450"
                    },
                    {
                      "firstName": "Edna",
                      "lastName": "Frank",
                      "title": "VP, Technology",
                      "email": "efrank@genepoint.com",
                      "phone": "(650) 867-3450"
                    }
                  ],
                  "links": [
                    {
                      "rel": "self",
                      "href": "accounts/0014I00001qsS4lQAE"
                    }
                  ]
                }

              
